In [ ]:
## Step 1: Load and Inspect Dataset
#First, I loaded the dataset into Pandas. Then I checked the first few rows to understand what data is available in the dataset.

import pandas as pd
df = pd.read_csv("Messy_Employment_India_Dataset.csv")
df.head()

,Status,Age Group,Education,Industry,Location,AI Risk,Years of Experience,Monthly Salary (INR),Date Recorded
0,EMPLOYED,25_34,high school,Technology,Urban,NaN,NaN,40700.0,1/1/2023
1,EMPLOYED,18-24,Diploma,Fintech,rural,moderate,NaN,17500.0,1/2/2023
2,EMPLOYED,25_34,High School,Retail,Delhi,Low,16.0,77600.0,1/3/2023
3,UNEMPLOYED,18-24,Masters,Retail,Urban,Low,30.0,100200.0,1/4/2023
4,NaN,45-54,Diploma,Fintech,Hyderabad,low,9.0,19500.0,1/5/2023

In [ ]:
## Step 2: Understand Dataset Structure and Data Types
#This step helps us understand the number of records, available columns, data types, and missing values.

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Status                1732 non-null   object
 1   Age Group             1768 non-null   object
 2   Education             1804 non-null   object
 3   Industry              1799 non-null   object
 4   Location              1787 non-null   object
 5   AI Risk               1716 non-null   object
 6   Years of Experience   980 non-null    float64
 7   Monthly Salary (INR)  1613 non-null   float64
 8   Date Recorded         2000 non-null   object
dtypes: float64(2), object(7)
memory usage: 140.8+ KB

Index(['Status', 'Age Group', 'Education', 'Industry', 'Location', 'AI Risk',
       'Years of Experience', 'Monthly Salary (INR)', 'Date Recorded'],
      dtype='object')

In [ ]:
df.shape

(2000, 9)

In [ ]:
df.columns

Index(['Status', 'Age Group', 'Education', 'Industry', 'Location', 'AI Risk',
       'Years of Experience', 'Monthly Salary (INR)', 'Date Recorded'],
      dtype='object')

In [ ]:
## Step 3: Identify and Handle Missing Values
#Missing values reduce data quality. Categorical columns are filled using the mode, while numerical columns are filled using the median.
df.isnull().sum()

Status                   268
Age Group                232
Education                196
Industry                 201
Location                 213
AI Risk                  284
Years of Experience     1020
Monthly Salary (INR)     387
Date Recorded              0
dtype: int64

In [ ]:
## Step 4: Remove Duplicate Records
#Duplicate records can lead to inaccurate analysis. These records are identified and removed.

print("Duplicate Rows:", df.duplicated().sum())
df.drop_duplicates(inplace=True)
print("Duplicate Rows After Cleaning:", df.duplicated().sum())

Duplicate Rows: 0
Duplicate Rows After Cleaning: 0

In [ ]:
## Step 5: Correct Inconsistent Formatting
#Text values often contain extra spaces and inconsistent capitalization. These issues are corrected.

for col in df.select_dtypes(include='object'):
    df[col] = df[col].str.strip()

In [ ]:
## Step 6: Fix Data Type Issues
#The Date Recorded column should be stored as a datetime data type for proper analysis.

df['Date Recorded'] = pd.to_datetime(
    df['Date Recorded'],
    errors='coerce'
)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Status                1732 non-null   object
 1   Age Group             1768 non-null   object
 2   Education             1804 non-null   object
 3   Industry              1799 non-null   object
 4   Location              1787 non-null   object
 5   AI Risk               1716 non-null   object
 6   Years of Experience   980 non-null    float64
 7   Monthly Salary (INR)  1613 non-null   float64
 8   Date Recorded         2000 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(6)
memory usage: 140.8+ KB

In [ ]:
## Step 7: Detect and Handle Outliers
#Outliers in salary values are identified using the IQR method and removed.

Q1 = df['Monthly Salary (INR)'].quantile(0.25)
Q3 = df['Monthly Salary (INR)'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df = df[
    (df['Monthly Salary (INR)'] >= lower) &
    (df['Monthly Salary (INR)'] <= upper)
]

In [ ]:
## Step 8: Rename and Standardize Column Names
#Column names are converted into lowercase format and spaces are replaced with underscores.
df.columns = (
    df.columns
      .str.lower()
      .str.replace(" ", "_")
      .str.replace("(", "", regex=False)
      .str.replace(")", "", regex=False)
)
df.columns

Index(['status', 'age_group', 'education', 'industry', 'location', 'ai_risk',
       'years_of_experience', 'monthly_salary_inr', 'date_recorded'],
      dtype='object')

In [ ]:
## Step 9: Validate and Verify Cleaned Data
#The cleaned dataset is checked again to verify that all cleaning operations were successful.

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1613 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   status               1388 non-null   object
 1   age_group            1432 non-null   object
 2   education            1450 non-null   object
 3   industry             1450 non-null   object
 4   location             1444 non-null   object
 5   ai_risk              1380 non-null   object
 6   years_of_experience  812 non-null    float64
 7   monthly_salary_inr   1613 non-null   float64
 8   date_recorded        1613 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(6)
memory usage: 126.0+ KB

In [ ]:
df.isnull().sum()

status                 225
age_group              181
education              163
industry               163
location               169
ai_risk                233
years_of_experience    801
monthly_salary_inr       0
date_recorded            0
dtype: int64

In [ ]:
df.head()

,status,age_group,education,industry,location,ai_risk,years_of_experience,monthly_salary_inr,date_recorded
0,EMPLOYED,25_34,high school,Technology,Urban,NaN,NaN,40700.0,2023-01-01
1,EMPLOYED,18-24,Diploma,Fintech,rural,moderate,NaN,17500.0,2023-01-02
2,EMPLOYED,25_34,High School,Retail,Delhi,Low,16.0,77600.0,2023-01-03
3,UNEMPLOYED,18-24,Masters,Retail,Urban,Low,30.0,100200.0,2023-01-04
4,NaN,45-54,Diploma,Fintech,Hyderabad,low,9.0,19500.0,2023-01-05

In [ ]:
## Step 10: Export Final Cleaned Dataset
#The final cleaned dataset is exported as a CSV file for future use.

df.to_csv(
    "Cleaned_Employment_India_Dataset.csv",
    index=False
)
print("Dataset exported successfully!")

Dataset exported successfully!